services:
  - type: web
    name: vq-everything
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: GOOGLE_OAUTH_CLIENT_ID
        sync: false
      - key: GOOGLE_OAUTH_CLIENT_SECRET
        sync: false
      - key: FLASK_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        value: sqlite:////data/submissions.db
      - key: ADMIN_EMAIL
        sync: false
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
